### ISSUE TITLE
Possible error in LAI calculation

### ISSUE THREAD

**Issue by tucker-furniss** [LANDIS-II-Foundation/Extension-NECN-Succession#81]
I noticed that after updating from NECN v6.6 to v6.8+, the LAI values output via the LAI maps are _much_ higher (nearly double), even with the exact same input files. 

I tried to diagnose the issue by examining the calibrate-log with single cell runs. Indeed, for a single cell with no grass (but many trees), for the first month I get BaseLAI = 12.5 using NECN v6.6 and BaseLAI = 31 using NECN v6.8. The sum of the individual cohort LAI values ("LAI" column) for NECN v6.6 is 13.5, while for NECN v6.8 it is 31.5 ("TreeLAI" column). The LAI output map values for that site are 13 and 31, respectively. 

I am not sure what is going on here, but it may have to do with the competition_limit adjustment to maxlai. In v6.6, maxlai was adjusted by the competition_limit at line 580 of the CohortBiomass.cs file with the line: _maxlai = maxlai*competition_limit_, but that line has been deleted (and not replaced, as far as I can tell). It seems as though this may have been an accidental deletion. 

The problem this causes is that BaseLAI values are no longer being adjusted by other trees present at the site, so site LAI is a simple cumulative sum of the potential LAI of all trees at the site, rather than reaching a plateau as the site becomes increasingly filled with trees. This issue is evident in the table attached here. The two highlighted rows have similar biomass, and BaseLAI is the same for the oldest cohorts. For younger cohorts, BaseLAI for v6.6 decreases as the site fills up but BaseLAI for v6.8 is calculated for each tree independently, regardless of how full the site is. 

If this diagnosis is correct, the fix should be pretty simple (replace the old line _maxlai = maxlai*competition_limit_ at around line 555 in the CohortBiomass.cs file). But I know the LAI methodology is changing a bit to handle grass differently, so I'm not sure if that fix alone will solve the issue. 

Thanks!
-Tucker

![image](https://user-images.githubusercontent.com/81191951/173964538-41929a3b-d1ff-4c6a-b78b-7d95e16037de.png)

**Comment by rmscheller** [comment]
Tucker,

Did you add the GrowthLAI parameter to your FunctionalType table?  This was specifically introduced to control the rate of LAI increase.  Previously it had a default value of 0.47.

Zachary, 

Any thoughts here?

Rob

**Comment by tucker-furniss** [comment]
I did include GrowthLAI, I set it to the default value of 0.47 as I was trying to replicate the behavior of the prior version.

**Comment by ZacharyRobbins** [comment]
Hi all,
I believe this change was by design. There were two competing problems here, and yes this change fundamentally alters the model's parameterization.  The problem we aimed to solve was the super penalization of young cohorts. As Tucker says the LAI of young cohorts was curtailed in 6.6 to the maxlai with trees limited to the remaining lai space.  This was convenient because it allowed LAI to be capped in a way that did not require too much parameterization of competition. It was inconvenient in that it penalized young cohorts both for their lack of lai (which limits growth) and through the lai competition limit (ei, the lack of sun reaching the understory). This resulted in young cohorts never growing except in the most open scenarios. 
These functions are 
 calculate_LAI_Competition
  calculateLAI_Limit
  
  
We in 6.8 opted for the alternative which is that the maximum lai should be the emergent property of the competition cohorts, rather than mitigated top down, this requires a reparameterization of the functional groups to get lai and growth values that reflect observation, without a top-down cap on lai. The same functionality should exist in the current set-up, where both factors limit growth, however, they are less hard capped. 

I think the main goal was to remove the double penalization of young cohorts, which appear to prevent them from escaping age one even in the event of relatively modest light conditions. 

Happy to clarify more, or discuss other implementation. 
-Z

**Comment by tucker-furniss** [comment]
Hi Zachary,

Thanks for the detailed reply. I think I understand the change (and the reasoning behind it), but I don't quite understand how exactly to reparameterize to produce more realistic (< ~10) LAI values. Would this be done primarily through tuning GrowthLAI parameter for different functional groups? The NECN v6.8 example scenario also produces high (up to 14) LAI values, so I am struggling to find an example parameterization that produces LAI values within a more reasonable range. 

Thanks!
Tucker

**Comment by ZacharyRobbins** [comment]
Hi Tucker, 
Please see the difference between the example, and the version we used in the Southern Apps.  I would start with max LAI, and adjust the parameters related to growthvialai, so that each cohort is growing at a previously parameterized pace. Attached are the histograms for time step 5 and timestep 90. I think they do a reasonable job at keeping LAI in range. 

[NECN_Functional_Table_Example.csv](https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/files/9073955/NECN_Functional_Table_Example.csv)
[NECN_Functional_Table_1_1.csv](https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/files/9073957/NECN_Functional_Table_1_1.csv)

![image](https://user-images.githubusercontent.com/25291127/178039699-b0ca3e4e-fe77-4047-98bb-80af0d7de444.png)

![image](https://user-images.githubusercontent.com/25291127/178039730-139779e0-60ae-482e-aac3-9a8aab245f18.png)
